GET http://localhost:3000/todos/?category=LOW
###
GET http://localhost:3000/todos/6/
###
GET http://localhost:3000/agenda/?date=2020-12-22
###
POST http://localhost:3000/todos/
Content-Type: application/json
{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}
###
PUT http://localhost:3000/todos/1/
Content-Type: application/json
{ "priority": "HIGH" }
###
DELETE http://localhost:3000/todos/6/
